FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json* ./
RUN npm install --include=dev

COPY src/config ./src/config
COPY nodemon.json ./
COPY .version* ./

EXPOSE 8070

CMD npm run dev-in-docker
