FROM node:25-bookworm-slim

WORKDIR /app

ENV CI=true
ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./
RUN npm install --global pnpm@10.29.2
RUN pnpm install --frozen-lockfile

COPY src/config ./src/config
COPY .version* ./

EXPOSE 8070

CMD ["pnpm", "run", "dev-in-docker"]
