services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8070:8070
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./.version:/app/.version
      - weather_node_modules:/app/node_modules
    restart: always
    environment:
      - ENV_ID=dev
      - NODE_OPTIONS=--enable-source-maps
    command: pnpm run dev-in-docker
    networks:
      - gratheon_default

networks:
  gratheon_default:
    external: true

volumes:
  weather_node_modules:
