services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8070:8070
    volumes:
      - .:/app
    restart: always
    environment:
      - ENV_ID=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - HISTORICAL_WEATHER_CACHE_TTL_SECONDS=1800
    command: sh -c "go mod download && go run ."
    networks:
      - gratheon_default

networks:
  gratheon_default:
    external: true
