FROM platformatic/node-caged:25-slim

WORKDIR /app

ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm@10.29.2
RUN pnpm install --frozen-lockfile

COPY src/config ./src/config
COPY .version* ./

EXPOSE 8070

CMD ["pnpm", "run", "dev-in-docker"]
