name: deploy
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: pull
        working-directory: /www/weather/
        run: git pull
        
      - name: restart
        working-directory: /www/weather/
        run: ./restart.sh